### ISSUE TITLE
CSS counter-set works differently from browsers

### ISSUE THREAD

**Issue by yamahige** [vivliostyle/vivliostyle.js#1390] opened 2024-10-12 05:07 UTC
**Describe the bug**
This is a case of custom ordered list with custom counter and `::before` pseudo element. When `counter-set` set to `li` as `style="counter-set: my-counter 99;"`, the generated number for the `li` is "100" in Vivliostyle while "99" in Chrome browser. Also "100" in Chrome browser when `counter-increment` is set to `li::before` pseudo element.

**To Reproduce**
Sample use `counters()` function.
<https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/yamahige/e7c6715703be6271a46f9e1a101d6b91/raw/bb40e78b31bd559047ed3a1452947daf898d95ac/list-counter-set.html>

**Expected behavior**
I'm not sure that `counter-set` should work differently whether `counter-increment` set to `li` or `li::before`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Safari, Firefox, Edge

**Screenshots**

Vivliostyle:
<img width="940" alt="Vivliostyle" src="https://github.com/user-attachments/assets/ce115101-593d-4877-9437-87a3598ca5e3">

Chrome browser:
<img width="432" alt="Chrome-browser" src="https://github.com/user-attachments/assets/a9dde833-4993-4608-92b1-6b83a92880e7">

**Comment by yamahige** [comment] 2024-10-12 05:33
Seemingly, does not support the implicit `list-item` counter. I'll open another issue for that.

**Comment by MurakamiShinyu** [comment] 2024-10-12 09:14
The problem is in the processing order of `counter-set` and `counter-increment`. The spec https://drafts.csswg.org/css-lists/#auto-numbering says:

> Resolving [counter](https://drafts.csswg.org/css-lists/#counter) values on a given element is a multi-step process:
> 
> 1. Existing counters are [inherited](https://drafts.csswg.org/css-lists/#inherit-counters) from previous elements.
> 
> 2. New counters are [instantiated](https://drafts.csswg.org/css-lists/#instantiate-counter) ([counter-reset](https://drafts.csswg.org/css-lists/#propdef-counter-reset)).
> 
> 3. Counter values are incremented ([counter-increment](https://drafts.csswg.org/css-lists/#propdef-counter-increment)).
> 
> 4. Counter values are explicitly set ([counter-set](https://drafts.csswg.org/css-lists/#propdef-counter-set)).
> 
> 5. Counter values are used ([counter()](https://drafts.csswg.org/css-lists/#funcdef-counter)/[counters()](https://drafts.csswg.org/css-lists/#funcdef-counters)). 

In this spec, `counter-set` is after `counter-increment`, so the incremented value must be overwritten by the set value. In the Vivliostyle.js's  implementation it is opposite.

https://github.com/vivliostyle/vivliostyle.js/blob/49970360cebec5e9b692c48b419a281c5edecf21/packages/core/src/vivliostyle/css-cascade.ts#L3110-L3129

**Comment by MurakamiShinyu** [comment] 2024-10-17 14:37
Fixed in PR #1396.

Test: https://vivliostyle-git-fix-issue1390-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/yamahige/e7c6715703be6271a46f9e1a101d6b91/raw/bb40e78b31bd559047ed3a1452947daf898d95ac/list-counter-set.html

**Closed as completed** 2024-10-17 14:38 UTC
Labels: bug

**Comment by MurakamiShinyu** [comment] 2024-10-18 06:11
After the fix of list-item counter issue (#1397), the result of the test sample is the same as the browser's.

Test: https://vivliostyle-git-fix-issue1391-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/yamahige/e7c6715703be6271a46f9e1a101d6b91/raw/bb40e78b31bd559047ed3a1452947daf898d95ac/list-counter-set.html

Screenshot:
![Screenshot 2024-10-18 15 07 29](https://github.com/user-attachments/assets/880e234c-638f-4a49-a1b4-1d855ebe4989)
