### ISSUE TITLE
Text does not flow around floated elements when rendering Wikipedia pages

### ISSUE THREAD

**Issue by tgr** [vivliostyle/vivliostyle.js#371] opened 2017-07-04 22:16 UTC
While trying to render the Wikipedia article Berlin, floated elements are displayed as if they were plain blocks. [Test page](http://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#x=https://en.wikipedia.org/api/rest_v1/page/html/Berlin/789016409/dafce1d2-60f8-11e7-94fe-c76bc93369a4) (using the vivliostyle.github.io installation with Chrome version 59.0.3071.86 (64-bit official build) on Ubuntu 16.04) - compare with  [original](https://en.wikipedia.org/api/rest_v1/page/html/Berlin/789016409/dafce1d2-60f8-11e7-94fe-c76bc93369a4). Images tend to be floated in the original but take up a full line in vivliostyle's rendering. This seems to be specific to images - for example, the stats table in the Immigration section is floated correctly.

**Comment by kwkbtr** [comment] 2017-07-05 01:41
The `float` property is ignored due to a problem of Vivliostyle's CSS parser when the stylesheet contains a syntax error.
In this case, the stylesheet contains the following declaration, which has a syntax error (`!ie`):
```css
vertical-align:middle !ie
```

When Vivliostyle's CSS parser encounters such an error, it gives up parsing the rest styles after the error, instead of simply skipping the declaration with the error.
This behavior of the CSS parser should be fixed to match CSS Syntax spec.

Related issue: #200

**Comment by MurakamiShinyu** [comment] 2022-10-19 05:45
I can't reproduce this old issue (5 years ago) because the original test data is not found now, but I believe this problem has already been resolved. Vivliostyle's CSS parser has been improved and fixed the problem.

**Closed as completed by MurakamiShinyu** 2022-10-19 05:45 UTC
Labels: bug
