### ISSUE TITLE
CSS text-align property does't work with Chrome extension

### ISSUE THREAD

**Issue by bobbytung** [vivliostyle/vivliostyle.js#19] opened 2015-05-08 06:52 UTC
[Here](https://www.dropbox.com/s/7vw5aek85dt6hun/pic1.png) is a sample. Second line is date with CSS property text-align:right. it's ok with browser view but doesn't work when paginated by the extension.

**Comment by kwkbtr** [comment] 2015-05-12 09:01
The second line （森鴎外） of [this sample](http://vivliostyle.github.io/vivliostyle.js/samples/variable-page-size/ja-vertical/Takasebune/main.xhtml) is styled with `text-align: right` and works fine with the Chrome extension.

Could you post a minimum sample that doesn't work?

**Comment by frivoal** [comment] 2015-12-10 02:48
Cannot reproduce, closing. Please reopen with details about reproduction if you still see it.

**Closed as completed by frivoal** 2015-12-10 02:48 UTC
Labels: question
