### ISSUE TITLE
selectors should be case insensitive

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle.js#95] opened 2015-12-02 07:16 UTC

**Comment by johanneswilm** [comment] 2015-12-21 17:40
Do we have particular selectors that do not work? 

Trying to test it on the @page selector, etc. seems to show that they are case insensitive so far. Also the css parser seems to convert to lower case when needed.

**Comment by johanneswilm** [comment] 2015-12-21 21:40
I guess you must be referring to element names in selectors.

**Comment by kwkbtr** [comment] 2015-12-21 23:37
Yes, at least element names selectors should be changed to be case insensitive.
I haven't checked if other selectors (class, attribute names/values etc.) are already case insensitive or not.

**Comment by johanneswilm** [comment] 2015-12-21 23:40
Ok, yes, I saw some of the others were already case insensitive. I will first try to make it work for elements, and if that works, I will check the other ones as well.

**Comment by johanneswilm** [comment] 2016-01-07 20:29
Continuing from the chat with @kwkbtr 

After a lot of investigation, it seems this can't really be done in combination with #106 without changing the order of how things are done. Currently it looks like this is the order:
1. resolving of the cascading of all CSS
2. analysis of document it has to apply CSS on, including finding the content type
3. do css selector matching, apply CSS

​the problem is, the cascading done in 1 should differ based on the contentType found in 2. For a lot of things there may not be much of a difference because one can simple compare a lowercase element/attribute name with a lowercase selector name in 3.

​But if you have both h1 {color:red} and H1 {color:blue} in the CSS, their order is important if the contentType is HTML. So we need to know the contentType we currently get in stage 2 already before doing the cascading of stage 1.

**Comment by kwkbtr** [comment] 2016-01-08 03:10
When constructing cascading chains in 1, the order of each rule is stored with the specificity of the selector.
(See https://github.com/vivliostyle/vivliostyle.js/blob/a6bf187cc90b1558670a6898ed292938422da210/src/adapt/csscasc.js#L2671)
So, for HTML (not XHTML), at stage 3 we can simply apply both of h1 and H1 rules because the rule application mechanism already takes the order and the specificity into account.

**Comment by kwkbtr** [comment] 2016-01-14 03:15
Fixed by #134.

**Closed as completed by kwkbtr** 2016-01-14 03:15 UTC
Labels: bug, spec conformance
